/**
 * Assistant-skill catalog (ADR-0008).
 *
 * The SSOT for every bundled assistant skill is `docs/skills/<name>/SKILL.md`,
 * shipped in the package `files` list. This module locates that source tree —
 * whether running from the repo (dev / dogfood) or from an installed npm
 * package (where `docs/skills` sits next to `dist/`) — and enumerates the
 * bundled skills found there.
 *
 * **Standalone binary (Issue #445)**: a `bun build --compile` binary has no
 * `docs/skills` on disk, so the lookup above finds nothing. It falls back to
 * {@link EMBEDDED_SKILLS} — the same catalog inlined as source (generated by
 * `scripts/generate-embedded-skills.mjs`), which `--compile` carries because
 * the module graph references it statically. Callers read a skill's body
 * through {@link readSkillSource} rather than `readFileSync(sourcePath)` so
 * both channels behave identically.
 *
 * No heavy dependencies: only `node:fs` / `node:path`, so the CLI can lazy-load
 * it cheaply (NFR-PRF-1). The embedded catalog is a plain string table that is
 * only parsed when this module is loaded (i.e. by the skills commands).
 */
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { EMBEDDED_SKILLS } from "./embedded.ts";

/** The single SKILL file name authored per skill directory. */
export const SKILL_FILE = "SKILL.md";

/** Agent hosts that assistant skills install into (ADR-0008). */
export const HOSTS = {
  /** Claude Code reads `.claude/skills/`. */
  claude: ".claude/skills",
  /** Codex / Copilot / Gemini read `.agents/skills/`. */
  agents: ".agents/skills",
} as const;

export type Host = keyof typeof HOSTS;

/** Install scopes selecting which host dir(s) to write (`--scope`). */
export const SCOPES = ["claude", "agents", "all"] as const;
export type Scope = (typeof SCOPES)[number];

/** Resolve a scope to the concrete host list it covers. */
export function scopeHosts(scope: Scope): Host[] {
  return scope === "all" ? ["claude", "agents"] : [scope];
}

/** A bundled skill: its `name` and where its SSOT `SKILL.md` comes from. */
export interface BundledSkill {
  readonly name: string;
  /**
   * Absolute path to the SSOT `SKILL.md` on disk, or the display label
   * `<embedded>/<name>/SKILL.md` when the body comes from the embedded
   * catalog (the standalone binary has no `docs/skills` to point at).
   * Never read this directly — use {@link readSkillSource}.
   */
  readonly sourcePath: string;
  /** True when the body lives in {@link EMBEDDED_SKILLS} rather than on disk. */
  readonly embedded?: boolean;
}

/** Display label used as `sourcePath` for an embedded skill (no disk path exists). */
export function embeddedSourceLabel(name: string): string {
  return `<embedded>/${name}/${SKILL_FILE}`;
}

/**
 * Read a bundled skill's `SKILL.md` body, from disk or from the embedded
 * catalog. The single seam every caller goes through, so the repo / npm
 * (filesystem) and binary (embedded) channels stay behaviourally identical.
 */
export function readSkillSource(skill: BundledSkill): string {
  if (skill.embedded) {
    const body = EMBEDDED_SKILLS[skill.name];
    if (body === undefined) {
      throw new Error(`embedded skill '${skill.name}' not found in the compiled catalog`);
    }
    return body;
  }
  return readFileSync(skill.sourcePath, "utf8");
}

/** The embedded catalog as {@link BundledSkill}s (sorted; used as the fallback). */
export function listEmbeddedSkills(): BundledSkill[] {
  return Object.keys(EMBEDDED_SKILLS)
    .sort((a, b) => a.localeCompare(b))
    .map((name) => ({ name, sourcePath: embeddedSourceLabel(name), embedded: true }));
}

/**
 * Locate the bundled `docs/skills` directory by walking up from this module.
 *
 * Works both in-repo (`src/skills/` → repo root holds `docs/skills`) and when
 * installed (`dist/` → package root holds `docs/skills`, per package.json
 * `files`). Returns `null` when no candidate exists.
 */
export function resolveSkillsSource(
  startDir: string = dirname(fileURLToPath(import.meta.url)),
): string | null {
  let dir = startDir;
  // Walk up to the filesystem root looking for a `docs/skills` directory.
  for (;;) {
    const candidate = join(dir, "docs", "skills");
    if (existsSync(candidate) && statSync(candidate).isDirectory()) return candidate;
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

/**
 * Enumerate bundled skills under `sourceDir` (defaults to the resolved source).
 *
 * A directory counts as a skill iff it contains a `SKILL.md`. Results are
 * sorted by name for deterministic output. When no on-disk source exists (the
 * standalone binary), falls back to the embedded catalog (Issue #445); only an
 * empty embedded catalog — which the drift test rules out — throws.
 */
export function listBundledSkills(
  sourceDir: string | null = resolveSkillsSource(),
): BundledSkill[] {
  if (sourceDir === null) {
    const embedded = listEmbeddedSkills();
    if (embedded.length > 0) return embedded;
    throw new Error(
      "could not locate bundled skills (docs/skills/); reinstall the package or run from the repo",
    );
  }
  const skills: BundledSkill[] = [];
  for (const entry of readdirSync(sourceDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const sourcePath = join(sourceDir, entry.name, SKILL_FILE);
    if (existsSync(sourcePath)) skills.push({ name: entry.name, sourcePath });
  }
  skills.sort((a, b) => a.name.localeCompare(b.name));
  return skills;
}
